name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - name: Multiple Commands
        run: |
          echo "Command 1"
          echo "Command 2"
          
  clone:
    needs: [first-job]
    runs-on: windows-latest
    steps:
      - name: Klone das Repo
        uses: actions/checkout@v3
      - name: Zeige den Inhalt an
        run: ls
        

  
