name: Testing Token
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * 6 *'
    
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        with:
          repository: alfeilex/git-action-sandbox
          path: sandbox
          token: ${{ secrets.PUSH_TOKEN }}
      - name: add txt file
        run: |
          cd sandbox
          touch text.txt
          ls
      - name: Commit and push to sandbox
        run: |
          cd sandbox
          ls
          git add .
          git config --global user.name ${{ secrets.BUILD_USER }}
          git config --global user.email ${{ secrets.BUILD_USER_EMAIL }}
          git commit -m "Update urls"
          git push

